### PR TITLE
Revert "Lunar linecol gradient"

### PR DESCRIPTION
**Pull request by R-CoderDotCom**
Reverts R-CoderDotCom/calendR#13

### CODE REVIEW

**Comment by mschilli87** [comment]
@R-CoderDotCom: I am confused: You merged my PR and reverted it again without any comments. Was this intended? Do you want me to create a new PR for these changes? Is there anything you want me to change about it? Or are you not interested in these changes?

**Comment by R-CoderDotCom** [comment]
Hi! Sorry for this! Your addition is really cool but the package has two authors and the other decided not to add more arguments to the function, as there are a lot already, so after discussing about it I had to undo the changes for now.

Best regards

**Comment by mschilli87** [comment]
Alright. No need to apologize.
I really like the package as it saved me a lot of work. I was about to implement something very similar for myself and this turned out to be a great base for my needs. However, I need several features missing from the package (like different text colors for different days, multiple texts per day - and thus variable text positioning within the day field - etc.) that I was planning to submit as PRs as well. I understand if you decide not to merge more features to keep the complexity and maintenance burden low.
I guess I'll maintain my own fork then. Feel free to collaborate there if you have feature ideas you cannot agree amongst the two of you. I might be interested. :wink:
For now, I'll refrain from refactoring existing code to keep my fork as close as possible to your code base. This way, if you change your mind or decide to merge specific features I am adding, it should be easy for you to merge them. For me on the other hand, this should make it easier to keep up with your future improvements.
However, I won't open PR here unless you ask me to do so.
If you want to see what I am up to, you can subscribe to my fork. :wink:
Also, if you feel I diverge too much or prefer my code not to be associated with your package for other reasons, don't hesitate to reach out. In this case I'd be perfectly fine with picking another name or even creating a hard fork from your repository. Just note that this would make cherry-picking code from each other more difficult.

If anyone else watching this repo and/or maintaining a fork for similar reasons would be up for collaborating, please just contact me.

**Comment by R-CoderDotCom** [comment]
Sounds great! Thank you! I have subscribed to your fork to follow up your updates. Your ideas are great and really appreciated.


P.D. Note that you can add multiple texts per day with \n. Related to this, I always wanted to use [ggfittext](https://wilkox.org/ggfittext/) to fit the texts inside the days when the text is too long, but never had the time to try. This will also allow to customize the position and the contrast of the text against the background.

**Comment by mschilli87** [comment]
Thx for the suggestion. I'll look into it. Though probanly not for the first implementation. Regarding multiple texts with `\n`, that's what I did as well at first until I noticed I'd need different colors for two texts sharing the same date. I'll try to get as much done as I can in the next days. If nobody else get's involve I'll probably be less active until the end of next year, at which point I'll be generating my 2023 calender which will make me realize what improvements I *need* compared to the 2022 one. 😉

**Pull request merged**
